version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: title
        must_exclude:
          regex: ^\[WIP\]
      - do: label
        must_exclude:
          regex: 'wip'
      - do: label
        must_exclude:
          regex: 'DO NOT MERGE'   
      - do: description
        no_empty:
          enabled: falses