# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: Xcode@5
  displayName: 'Build the app using Xcode'
  inputs:
    actions: 'build'
    sdk: 'iphonesimulator13.1'
    scheme: 'Canvas'
    configuration: 'Debug'
    xcWorkspacePath: 'Canvas.xcworkspace'
    useXcpretty: 'false'
    xcodeVersion: '11.1' # Options: 8, 9, 10, default, specifyPath
