# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- script: cd Javascript ; npm install ; cd ..
  displayName: Install NPM Dependencies
- script: cd Javascript ; npm run build ; cd ..
  displayName: Run Webpack Bundle Script
- script: carthage bootstrap
  displayName: Carthage Dependencies 
- task: Xcode@5
  displayName: 'Build the app using Xcode'
  inputs:
    actions: 'build'
    sdk: 'iphonesimulator'
    scheme: 'Canvas'
    configuration: 'Debug'
    xcWorkspacePath: 'Canvas.xcodeproj'
    useXcpretty: 'false'
    xcodeVersion: '11' # Options: 8, 9, 10, default, specifyPath
